# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "data-uri-to-buffer-3.0.1" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-3.0.1.tgz";
        sha512 = "WboRycPNsVw3B3TL559F7kuBUM4d8CgMEvk6xEJlOp7OBPjt6G7z8WMWlD2rOFZLk6OYfFIUGsCOWzcQH9K2og==";
      };
    };
    "esm-3.2.25" = {
      name = "esm";
      packageName = "esm";
      version = "3.2.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/esm/-/esm-3.2.25.tgz";
        sha512 = "U1suiZ2oDVWv4zPO56S0NcR5QriEahGtdN2OR6FiOG4WJvcjBVFB0qI4+eKoWFH483PKGuLuu6V8Z4T5g63UVA==";
      };
    };
    "fetch-blob-1.0.7" = {
      name = "fetch-blob";
      packageName = "fetch-blob";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fetch-blob/-/fetch-blob-1.0.7.tgz";
        sha512 = "mJyUUpl2bOpjV5FdUNbVTMNYBLESg3q4mvkgNcNlxQqI+l9K0rT7OQLBxrn1w8U+/iof5hWcHBbeYwBm4jcBOA==";
      };
    };
    "node-fetch-3.0.0-beta.6-exportfix" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "3.0.0-beta.6-exportfix";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-3.0.0-beta.6-exportfix.tgz";
        sha512 = "jhW2arLPAddi7q04JxlQtApqMQF8GxlGZV+wj5/WuDz3hpDTnAU9haJ5Fi2a0N3b4e728O4EIVACNq9nDCzLYw==";
      };
    };
  };
  args = {
    name = "_at_jolharg_slash_oeis";
    packageName = "@jolharg/oeis";
    version = "1.1.0";
    src = ./.;
    dependencies = [
      sources."data-uri-to-buffer-3.0.1"
      sources."esm-3.2.25"
      sources."fetch-blob-1.0.7"
      sources."node-fetch-3.0.0-beta.6-exportfix"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "OEIS information extractor";
      homepage = "https://github.com/dandart/oeis#readme";
      license = "WTFPL";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}